export const SENSORDATA_REQUEST = "SENSORDATA_REQUEST"
export const SENSORDATA_SUCCESS = "SENSORDATA_SUCCESS"
export const SENSORDATA_FAIL = "SENSORDATA_FAIL"

export const SENSORDATA_LAST_TEMPERATURE_REQUEST = "SENSORDATA_LAST_TEMPERATURE_REQUEST"
export const SENSORDATA_LAST_TEMPERATURE_SUCCESS = "SENSORDATA_LAST_TEMPERATURE_SUCCESS"
export const SENSORDATA_LAST_TEMPERATURE_FAIL = "SENSORDATA_LAST_TEMPERATURE_FAIL"
